### PR TITLE
Added handlers for two more exceptions

### PR DESCRIPTION
**Pull request by antrix190**
Handlers added for following exceptions : 
1. RestClientException
2. MultipartException

### CODE REVIEW

**Comment by antrix190** [comment]
@mlk Build is failing for some reason. Can you please help?

**Comment by mlk** [comment]
Good day @antrix190 .
Thanks for your contribution. I'm not sure what has caused the build to fail, however I do know that Circle 1 has been deprecated and I need to upgrade to Circle 2 ( #12 ). I'll try and find the time to do this work over the new few days.

Thanks,
      Michael

**Comment by antrix190** [comment]
Okay could you please review the code at the same time?

**Comment by mlk** [comment]
Good day @antrix190 . Could you please:

1. Remove the `log.error`s
2. Add new lines after each part of the builder (to match the other methods)

Cheers

**Comment by mlk** [comment]
Ignore my comment on the log.error, it looks like we are inconsistent in them. 

I'll add a note to add them to the missing items.

**Comment by antrix190** [comment]
@mlk Done as requested.

**Comment by mlk** [comment]
Thanks @antrix190 , one last thing, can you please add tests for the two new exceptions. Once they are done I'll be happy to merge.

**Comment by antrix190** [comment]
Sure,

**Review by mlk — APPROVED** [review]

**Comment by mlk** [comment]
The release should happen automatically and the next version will include the changes.

**Comment by mlk** [comment]
This is part of release 1.1.78.

**Pull request merged**
